### ISSUE TITLE
Not properly capturing special characters when getting ascii characters.

### ISSUE THREAD

**Issue by Broken-Admin** [tr4cefl0w/0x00sec#1]
# Replication
- Start up program
- Open a browser or notepad
- Type in regular ascii characters, also using backspace and other special characters
 
With viewing the logs, you can see that although the keys are logged, special characters are not.

**Comment by tr4cefl0w** [comment]
Thanks for reporting. The keylogger what updated following the last post on 0x00sec. Support for virtual keys is present but to keep the log file clean I chose not to write them in the file. Nothing prevents you to do so. You simply have to add the key to the `VIRTUAL_KEY` dictionary if it's not already there and add a conditional statement to write that key in the log file.
